### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/antlr-feedstock#11]
Try @pedro-vicente's Visual Studio projects from https://github.com/conda-forge/nco-feedstock/issues/6#issuecomment-343271509

xref #13

**Comment by ocefpaf** [comment]
@pedro-vicente the proj file seems to be working fine for win32 but we are getting an error on win64:

```
Done Building Project "C:\bld\antlr_1510924152766\work\antlr-2.7.7\lib\cpp\antlr.vcxproj" (default targets) -- FAILED.
Build FAILED.
"C:\bld\antlr_1510924152766\work\antlr-2.7.7\lib\cpp\antlr.vcxproj" (default target) (1) ->
(PrepareForBuild target) -> 
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(283,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Release|x64. [C:\bld\antlr_1510924152766\work\antlr-2.7.7\lib\cpp\antlr.vcxproj]
    0 Warning(s)
    1 Error(s)
```

Is that an easy fix? I was unable to build `nco` on `win32` and pretty soon conda-forge will drop support for win32 altogether.

**Comment by pedro-vicente** [comment]
@ocefpaf yes, the project is for win32. It's straightforward to generate one for Win64. Click on the drop down menu that says "win32", click "Configuration Manager", click again on the down menu that says "win32", select "New", choose "x64", click OK

**Comment by ocefpaf** [comment]
> @ocefpaf yes, the project is for win32. It's straightforward to generate one for Win64. Click on the drop down menu that says "win32", click "Configuration Manager", click again on the down menu that says "win32", select "New", choose "x64", click OK

I guess you mean to do that clicking using Visual Studio, right? I don't really have a Windows machine and AppVeyor only provide remote builds, not a GUI access :unamused:

**Comment by pedro-vicente** [comment]
here's the project

[antlr.zip](https://github.com/conda-forge/antlr-feedstock/files/1487989/antlr.zip)

**Comment by ocefpaf** [comment]
Done in #13 

Thanks @pedro-vicente!
