### ISSUE TITLE
This recipe installs gcc-java. We must fix that!

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/antlr-feedstock#4]
@jakirkham what is the status of your yum install proposal? @pelson or should we add `gcc-java` to the `Dockerfile`?

``` shell
if [[ $(uname) != Darwin ]]; then
    yum install -y gcc-java
fi
```

**Comment by jakirkham** [comment]
I think we like the proposal for `staged-recipes` it just needs cleanup. Not sure how it fairs at `conda-smithy`. Though I am still going through the last 6hrs of notifications, but we are getting close to the end. :wink:

**Comment by ocefpaf** [comment]
> Though I am still going through the last 6hrs of notifications

I know how that feels :smile: (Feel free to ignore most of my pings. I will ping you again anyways :stuck_out_tongue_closed_eyes:)

**Comment by jakirkham** [comment]
Here is what it looks like though ( https://github.com/conda-forge/conda-smithy/pull/135 ). Basically, you would add a `yum_requirements.txt` file that just has a list of packages. Take a look at this example ( https://github.com/conda-forge/pyopengl-feedstock/pull/3 ).

**Comment by jakirkham** [comment]
> I know how that feels :smile: (Feel free to ignore most of my pings. I will ping you again anyways :stuck_out_tongue_closed_eyes:)

I would much rather go through a giant backlog of notifications than see nothing. It means we are doing something right here. :wink:

**Comment by pelson** [comment]
Does the installer of antlr also need gcc-java installed to run, or is it just a build dependency?

**Comment by ocefpaf** [comment]
> Does the installer of antlr also need gcc-java installed to run, or is it just a build dependency?

Build only.

**Comment by jakirkham** [comment]
So, as to the particular case of using `gcj`. I would like to avoid it if possible as that project doesn't seem to have seen any [activity](https://gcc.gnu.org/java/) since 2009. :open_mouth: If there are some flags in configure to stop this, that would be awesome.

However, if that is not doable either because the flags don't exists or (hopefully not :pray:) people are relying on this functionality :fearful:, I believe it is included with Continuum's `gcc`. Though I don't think they are including the libraries that we would need. So, we might need to pick up those libraries another way.

**Comment by jakirkham** [comment]
Could we just add a recipe for OpenJDK instead and use that?

**Comment by ocefpaf** [comment]
> So, as to the particular case of using `gcj`. I would like to avoid it if possible as that project doesn't seem to have seen any activity since 2009. :open_mouth: If there are some flags in configure to stop this, that would be awesome.

I will take a look, but bare in mind that `antlr 2` is also very old and unsupported. We need `antlr` only to compile `nco`'s `ncap2`.

> However, if that is not doable either because the flags don't exists or (hopefully not :pray:) people are relying on this functionality :fearful:, I believe it is included with Continuum's `gcc`. Though I don't think they are including the libraries that we would need. So, we might need to pick up those libraries another way.

I will take a look at Continuum's `gcc`, but I believe that it is harmless to add gcc-java to the Docker image.

> Could we just add a recipe for OpenJDK instead?

Not sure. I will investigate that too.

**Comment by jakirkham** [comment]
According to the the documentation in their source, they support `--disable-java`. So, we should be able to just disable it. This is probably easiest until we figure out how we want to support Java.

Also, they support the following Java compilers in order `jikes`, `javac`, and `gcj`. So, if we have OpenJDK that should work (provides `javac`) and will be used preferentially to `gcj`. That seems like a much safer course. Particularly as `gcj` supports Java 1.4 and some of 1.5. Currently Java 1.8 is out and work is already being done to support Java 9.

I saw this [website](http://www.antlr.org/) and this [GitHub org](https://github.com/antlr). Are they any relation?

**Comment by ocefpaf** [comment]
> According to the the documentation in their source, they support `--disable-java`. So, we should be able to just disable it. This is probably easiest until we figure out how we want to support Java.

Thanks @jakirkham! I checked and `nco`'s `ncap2` worked just fine without java. So I am removing the java support. See #5.

> Also, they support the following Java compilers in order `jikes`, `javac`, and `gcj`. So, if we have OpenJDK that should work (provides `javac`) and will be used preferentially to `gcj`. That seems like a much safer course. Particularly as `gcj` supports Java 1.4 and some of 1.5. Currently Java 1.8 is out and work is already being done to support Java 9.

Don't think we'll need that as `antlr 2` is very old and we only need it for `nco`.

> I saw this [website](http://www.antlr.org/) and this [GitHub org](https://github.com/antlr). Are they any relation?

Yes. That is the modern version, but `nco` needs `antlr 2`.

**Comment by jakirkham** [comment]
If we need older versions of Java in the future, we can also visit that too.
