### ISSUE TITLE
Add antlr[version='>=2.7.7,<3'] to osx-arm64, is dependency for nco

### ISSUE THREAD

**Issue by LunarLanding** [conda-forge/antlr-feedstock#50]
### Comment:

Tried to build nco on osx-arm64, however got `antlr[version='>=2.7.7,<3']` not found in osx-arm64.
Can it be added?

**Comment by bollwyvl** [comment]
PRs welcome targeting https://github.com/conda-forge/antlr-feedstock/tree/antlr2, especially if you can actually test on that architecture. I'm not sure the steps that would be needed, and how much deeper in the stack it will take you.

**Comment by Tobias-Fischer** [comment]
Can nco target antlr4, which has builds for this platform?

**Comment by xylar** [comment]
@bollwyvl and @LunarLanding, I will work in this with @czender.

> Can nco target antlr4, which has builds for this platform?

@Tobias-Fischer, unfortunately not, see https://github.com/conda-forge/nco-feedstock/pull/165#issuecomment-1359545833

**Comment by zklaus** [comment]
I think we got this in #53. Please reopen if it is not so.
